name = "cglabs-backend"
main = "dist/worker.js"
compatibility_date = "2024-05-12"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "cglabs-db"
database_id = "506b182a-eb99-413e-9939-2f71300354c5"
migrations_dir = "migrations"

[site]
bucket = ""
