import type { PokemonId, PokemonConfig } from '@cglabs/shared';

export const POKEMON_MASCOTS: Record<PokemonId, PokemonConfig> = {
  pikachu: {
    id: 'pikachu',
    dexId: 25,
    name: 'Pikachu',
    archetype: 'Electric Innovator',
    motto: 'Sparking high-voltage breakthroughs with relentless energy.',
    emoji: '⚡',
    themeColor: '#eab308',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
  },
  charizard: {
    id: 'charizard',
    dexId: 6,
    name: 'Charizard',
    archetype: 'Flame Striker',
    motto: 'Blazing through barriers to launch moonshot pitches.',
    emoji: '🔥',
    themeColor: '#ef4444',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',
  },
  bulbasaur: {
    id: 'bulbasaur',
    dexId: 1,
    name: 'Bulbasaur',
    archetype: 'Organic Architect',
    motto: 'Building sustainable, scalable foundations from seed to canopy.',
    emoji: '🌿',
    themeColor: '#22c55e',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',
  },
  squirtle: {
    id: 'squirtle',
    dexId: 7,
    name: 'Squirtle',
    archetype: 'Torrential Executor',
    motto: 'Flowing smoothly around roadblocks with tactical precision.',
    emoji: '💧',
    themeColor: '#3b82f6',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png',
  },
  gengar: {
    id: 'gengar',
    dexId: 94,
    name: 'Gengar',
    archetype: 'Shadow Strategist',
    motto: 'Outmaneuvering competition with slick, unexpected maneuvers.',
    emoji: '👻',
    themeColor: '#a855f7',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png',
  },
  eevee: {
    id: 'eevee',
    dexId: 133,
    name: 'Eevee',
    archetype: 'Evolutionary Maker',
    motto: 'Adaptable to any domain, evolving to conquer any challenge.',
    emoji: '🦊',
    themeColor: '#d97706',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png',
  },
  mewtwo: {
    id: 'mewtwo',
    dexId: 150,
    name: 'Mewtwo',
    archetype: 'Psychic Visionary',
    motto: 'Calculating future trends with unparalleled strategic intellect.',
    emoji: '🔮',
    themeColor: '#8b5cf6',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png',
  },
  snorlax: {
    id: 'snorlax',
    dexId: 143,
    name: 'Snorlax',
    archetype: 'Resilient Tank',
    motto: 'Unshakable stamina under pressure, delivering giant results.',
    emoji: '💤',
    themeColor: '#475569',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png',
  },
  lucario: {
    id: 'lucario',
    dexId: 448,
    name: 'Lucario',
    archetype: 'Aura Master',
    motto: 'Sensing user needs and executing with razor focus.',
    emoji: '🥊',
    themeColor: '#0284c7',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png',
  },
  jigglypuff: {
    id: 'jigglypuff',
    dexId: 39,
    name: 'Jigglypuff',
    archetype: 'Vocal Orchestrator',
    motto: 'Captivating audiences with memorable, irresistible storytelling.',
    emoji: '🎤',
    themeColor: '#ec4899',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png',
  },
  blastoise: {
    id: 'blastoise',
    dexId: 9,
    name: 'Blastoise',
    archetype: 'Hydro Cannon Engineer',
    motto: 'Deploying high-pressure solutions with unstoppable momentum.',
    emoji: '🌊',
    themeColor: '#2563eb',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png',
  },
  dragonite: {
    id: 'dragonite',
    dexId: 149,
    name: 'Dragonite',
    archetype: 'Global Pathfinder',
    motto: 'Crossing oceans to deliver world-changing innovation.',
    emoji: '🐉',
    themeColor: '#f97316',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png',
  },
  mew: {
    id: 'mew',
    dexId: 151,
    name: 'Mew',
    archetype: 'Genesis Originator',
    motto: 'Unlocking infinite possibilities from foundational code.',
    emoji: '✨',
    themeColor: '#f472b6',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png',
  },
  gyarados: {
    id: 'gyarados',
    dexId: 130,
    name: 'Gyarados',
    archetype: 'Apex Disruptor',
    motto: 'Transforming quiet ideas into roaring market dominance.',
    emoji: '🐉',
    themeColor: '#0284c7',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png',
  },
  rayquaza: {
    id: 'rayquaza',
    dexId: 384,
    name: 'Rayquaza',
    archetype: 'Sky High Visionary',
    motto: 'Ascending above the clouds to command industry horizons.',
    emoji: '☁️',
    themeColor: '#16a34a',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/384.png',
  },
  gardevoir: {
    id: 'gardevoir',
    dexId: 282,
    name: 'Gardevoir',
    archetype: 'Empathetic Strategist',
    motto: 'Shielding teams and anticipating user emotions flawlessly.',
    emoji: '💚',
    themeColor: '#10b981',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/282.png',
  },
  garchomp: {
    id: 'garchomp',
    dexId: 445,
    name: 'Garchomp',
    archetype: 'Supersonic Velocity',
    motto: 'Tearing through backlogs at Mach speed.',
    emoji: '🦈',
    themeColor: '#1e40af',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/445.png',
  },
  greninja: {
    id: 'greninja',
    dexId: 658,
    name: 'Greninja',
    archetype: 'Stealth Operator',
    motto: 'Executing critical launches under cover of perfect focus.',
    emoji: '🥷',
    themeColor: '#3b82f6',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/658.png',
  },
  sceptile: {
    id: 'sceptile',
    dexId: 254,
    name: 'Sceptile',
    archetype: 'Agile Tactician',
    motto: 'Slashing through bloat to deliver razor-sharp features.',
    emoji: '🍃',
    themeColor: '#22c55e',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/254.png',
  },
  blaziken: {
    id: 'blaziken',
    dexId: 257,
    name: 'Blaziken',
    archetype: 'High-Impact Striker',
    motto: 'Leaping over obstacles with fiery passion and intensity.',
    emoji: '🔥',
    themeColor: '#dc2626',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/257.png',
  },
  tyranitar: {
    id: 'tyranitar',
    dexId: 248,
    name: 'Tyranitar',
    archetype: 'Unshakable Powerhouse',
    motto: 'Reshaping tech landscapes with massive structural power.',
    emoji: '🦖',
    themeColor: '#65a30d',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/248.png',
  },
  scizor: {
    id: 'scizor',
    dexId: 212,
    name: 'Scizor',
    archetype: 'Precision Cutter',
    motto: 'Metalsmithing bulletproof systems with laser accuracy.',
    emoji: '✂️',
    themeColor: '#e11d48',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/212.png',
  },
  umbreon: {
    id: 'umbreon',
    dexId: 197,
    name: 'Umbreon',
    archetype: 'Nocturnal Sentinel',
    motto: 'Guarding platform security in the darkest hours.',
    emoji: '🌙',
    themeColor: '#eab308',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/197.png',
  },
  espeon: {
    id: 'espeon',
    dexId: 196,
    name: 'Espeon',
    archetype: 'Solar Clairvoyant',
    motto: 'Predicting future tech paradigms before they emerge.',
    emoji: '☀️',
    themeColor: '#a855f7',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/196.png',
  },
  sylveon: {
    id: 'sylveon',
    dexId: 700,
    name: 'Sylveon',
    archetype: 'Harmonious Catalyst',
    motto: 'Uniting teams with joyful energy and smooth collaboration.',
    emoji: '🎀',
    themeColor: '#f472b6',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/700.png',
  },
  lapras: {
    id: 'lapras',
    dexId: 131,
    name: 'Lapras',
    archetype: 'Tranquil Navigator',
    motto: 'Ferrying complex projects across stormy waters peacefully.',
    emoji: '🐢',
    themeColor: '#0ea5e9',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png',
  },
  machamp: {
    id: 'machamp',
    dexId: 68,
    name: 'Machamp',
    archetype: 'Multi-Threaded Builder',
    motto: 'Handling four heavy tasks simultaneously without sweat.',
    emoji: '💪',
    themeColor: '#64748b',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png',
  },
  arcanine: {
    id: 'arcanine',
    dexId: 59,
    name: 'Arcanine',
    archetype: 'Majestic Leader',
    motto: 'Leading teams with fierce loyalty and legendary speed.',
    emoji: '🦁',
    themeColor: '#ea580c',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png',
  },
  psyduck: {
    id: 'psyduck',
    dexId: 54,
    name: 'Psyduck',
    archetype: 'Overthinking Genius',
    motto: 'Turning deep headaches into sudden strokes of brilliance.',
    emoji: '🦆',
    themeColor: '#facc15',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png',
  },
  togepi: {
    id: 'togepi',
    dexId: 175,
    name: 'Togepi',
    archetype: 'Lucky Incubator',
    motto: 'Nurturing early-stage ideas into magical successes.',
    emoji: '🥚',
    themeColor: '#fef08a',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/175.png',
  },
};

